language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt 
  - pip install coveralls
# command to run tests
env:
  - DJANGO_VERSION=1.3
script:
  - coverage run --source=elections manage.py test elections
  - coverage report -m
after_script:
  - coveralls --verbose
